# Generated by Django 5.2.6 on 2025-09-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("devices", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="device_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_by_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.teacher",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.attendancesession",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.classschedule",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.department"
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.subject"
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.subject"
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                through="attendance.SubjectEnrollment", to="users.student"
            ),
        ),
        migrations.AddField(
            model_name="subjectteacher",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.subject"
            ),
        ),
        migrations.AddField(
            model_name="subjectteacher",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                through="attendance.SubjectTeacher", to="users.teacher"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("session", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="classschedule",
            unique_together={
                (
                    "subject",
                    "day_of_week",
                    "start_time",
                    "academic_year",
                    "semester",
                    "section",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="subjectenrollment",
            unique_together={("subject", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectteacher",
            unique_together={("subject", "teacher")},
        ),
    ]
