# Generated by Django 5.2.6 on 2025-09-23 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=20, unique=True)),
                ("device_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("kiosk", "Attendance Kiosk"),
                            ("camera", "IP Camera"),
                            ("tablet", "Tablet Device"),
                        ],
                        default="kiosk",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("building", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("is_online", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("installed_date", models.DateField(auto_now_add=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("attendance", "Attendance Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
